import board

DISPLAY_MOSI = board.D10
DISPLAY_SCK = board.D8
DISPLAY_CS = board.D7
DISPLAY_DC = board.D6
DISPLAY_RST = board.D5
DISPLAY_BUSY = board.D4

DISPLAY_WIDTH = 250
DISPLAY_HEIGHT = 122

NFC_SDA = board.SDA
NFC_SCL = board.SCL
NFC_GPO = board.D1

NFC_I2C_ADDR_USER = 0x53
NFC_I2C_ADDR_SYSTEM = 0x57

BUTTON_LEFT = board.D0
BUTTON_SELECT = board.D9
BUTTON_RIGHT = board.D2

BUTTON_DEBOUNCE_MS = 25
BUTTON_LONG_PRESS_MS = 600

BATTERY_ADC_PIN = board.VBAT
BATTERY_MIN_VOLTAGE = 3.3
BATTERY_MAX_VOLTAGE = 4.2

DEVICE_NAME = "Akshat"